name: 📖 Documentation
description: Report a documentation issue or suggest an improvement
labels: ["documentation", "pending triage"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this documentation issue or suggestion!
  - type: textarea
    id: documentation-description
    attributes:
      label: Describe the change
      description: A clear and concise description of what you think should be changed, including the possible use cases and alternatives you have considered.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: content-urls
    attributes:
      label: URLs
      description: A list (or a link) to the URLs that you think should be changed (if applicable).
      placeholder: URLs
    validations:
      required: false
  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help?
